"""Turn a measured motion-profile.json into profile.js for the ted-ed-alive layer.

Usage:
    python -m scripts.style_refs.build_alive_profile \
        assets/references/ted-ed/motion-profile.json \
        assets/hyperframes/ted-ed-alive/profile.js

HyperFrames compositions may not fetch files at render time, so the numbers
are baked into a small script that sets window.TED_ED_ALIVE_PROFILE.
Values that could not be measured fall back to alive.js DEFAULTS.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

EASE = {"linear": "none", "ease-in": "sine.in", "ease-out": "sine.out", "ease-in-out": "sine.inOut"}


def build(profile: dict) -> dict:
    p = profile["pooled"]
    vids = [profile["videos"][k] for k in profile.get("pooled_from", profile["videos"].keys())]
    easing_counts: dict[str, int] = {}
    for v in vids:
        for k, n in v["camera_drift"]["easing"].items():
            easing_counts[k] = easing_counts.get(k, 0) + n
    ease = EASE[max(easing_counts, key=easing_counts.get)] if any(easing_counts.values()) else None

    fps = p.get("fps") or 24
    cadence = p.get("boil_cadence_seconds")
    # Real line boil means held linework changes on most beats. When the
    # typical held frame shows almost no line change, the references keep
    # their lines still and the layer must not wobble them.
    line_med = p.get("line_change_while_holding_median") or 0
    boil_on = line_med > 0.005 and (p.get("boil_amplitude_px") or 0) >= 1
    grain = p.get("grain_flicker_std")
    idle = p.get("idle_events_per_minute")
    out = {
        "stepFps": round(1 / cadence) if cadence else None,
        "boilCadenceSeconds": cadence if boil_on else 0,
        "boilAmplitudePx": p.get("boil_amplitude_px") if boil_on else 0,
        # flicker near codec noise (<1 grey level) means a fixed paper texture
        "grainFlickers": bool(grain and grain > 1.2),
        "driftPanPxPerS": p.get("drift_pan_px_per_s"),
        "driftZoomPctPerS": p.get("drift_zoom_pct_per_s"),
        "driftEase": ease,
        "shareOfShotsMoving": p.get("share_of_shots_moving"),
        "secondaryEventGapSeconds": round(60 / idle, 3) if idle else None,
        "measuredAtFps": fps,
    }
    return {k: v for k, v in out.items() if v is not None}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("profile_json", type=Path)
    ap.add_argument("out_js", type=Path)
    args = ap.parse_args()
    profile = json.loads(args.profile_json.read_text(encoding="utf-8"))
    values = build(profile)
    args.out_js.parent.mkdir(parents=True, exist_ok=True)
    args.out_js.write_text(
        "// Generated by scripts/style_refs/build_alive_profile.py from\n"
        f"// {args.profile_json.as_posix()} - do not edit by hand.\n"
        f"window.TED_ED_ALIVE_PROFILE = {json.dumps(values, indent=2)};\n",
        encoding="utf-8",
    )
    print(json.dumps(values, indent=2))


if __name__ == "__main__":
    main()
